[[bin]]
path = "luna/main.rs"
name = "luna"

[package]
name = "luna"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"
description = "Take your protein pills and put your helmet on."
repository = "https://github.com/clearloop/luna"
license = "GPL-3.0+"

[dependencies]
primitive = { path = "./core/primitive" }
black_hole = { path = "./core/black_hole" }
velvet_goldmine = { path = "./core/velvet_goldmine" }
guardians_of_galaxy = { path = "./core/guardians_of_galaxy" }

[workspace]
members = [
        "./core/primitive",
        "./core/black_hole",
        "./core/velvet_goldmine",
        "./core/guardians_of_galaxy"
]